title: Cyber Butler
description: HomePage for CyberButler

# remote_theme: pages-themes/hacker@v0.2.0
# show_downloads: false

plugins:
  # - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - extension/
  - backend/
  - LICENSE

# assets:
#   features:
#     liquid: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:title/
  - scope:
      path: "_posts"
    values:
      layout: "default"
      permalink: /:year/:month/:day/:title/

# liquid:
#   error_mode: strict
#   strict_filters: true

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
